# Use an official Playwright image as the base
FROM ://mcr.microsoft.com

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (if present)
COPY package*.json ./

# Install project dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Command to run the tests when the container starts
CMD ["npx", "playwright", "test"]